Add 'isXYZ' functions
grvcoelho/lando pull request #12
Opened 2016-12-18 18:47 UTC by joaolucasl

This PR adds the following files and its tests:
```
is-finite.js
is-function.js
is-integer.js
is-nan.js  
is-number.js
is-object.js
```

2016-12-18 21:54 UTC, joaolucasl commented on test/internals/is-number.js
> +  t.true(isNumber(NaN))
lol Javascript

2016-12-19 12:19 UTC, grvcoelho commented on test/internals/is-number.js
> +  t.true(isNumber(NaN))
:smile:

2016-12-19 12:19 UTC, grvcoelho commented on -
> +Uso: grep [OPÇÃO]... PADRÃO [ARQUIVO]...
lol, hahahaha @joaolucasl

2016-12-19 12:24 UTC, joaolucasl commented on -
> +Uso: grep [OPÇÃO]... PADRÃO [ARQUIVO]...
lol wat

2016-12-19 14:44 UTC, grvcoelho requested changes

2016-12-19 14:44 UTC, grvcoelho commented on lib/internals/is-finite.js
> +import _isNaN from './is-nan'
Why is everything with `_` before their names?

haha I know you probably mean private, but we could leave them off. :smile:

2016-12-19 14:53 UTC, joaolucasl commented on lib/internals/is-finite.js
> +import _isNaN from './is-nan'
So it doesn't override [JS's default `isNaN`](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/isNaN) function

2016-12-19 14:56 UTC, joaolucasl commented on lib/internals/is-finite.js
> +const _isFinite = x => !(!_isNumber(x) || _isNaN(x) || x === Infinity || x === -Infinity)
Same for `isFinite`, there's a [default JS function for that](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/isFinite).

`isNumber` has `_` for consistency

2016-12-19 14:57 UTC, joaolucasl commented on lib/internals/is-function.js
> +const _toStringIsGenerator = x => (Object.prototype.toString.call(x) === '[object GeneratorFunction]')
These have `_` for no actual reason, mostly being private (as in, not exposed)

2017-04-04 00:24 UTC, joaolucasl commented
Finally had the time to update this @grvcoelho. Mind givin' it a check?

2017-05-12 20:29 UTC, grvcoelho approved these changes

2017-05-12 20:29 UTC, merged